name: Build ipwnder
on: [push]
jobs:
  ipwnder-linux:
    strategy:
      matrix:
        arch:
          - runner: ubuntu-22.04
            name: x86_64
          - runner: ubuntu-22.04-arm
            name: aarch64

    name: ipwnder-linux-${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y aria2 libusb-1.0-0-dev clang lld
          sudo apt remove -y libssl-dev libusb-1.0-0-dev

          aria2c https://github.com/libusb/libusb/releases/download/v1.0.28/libusb-1.0.28.tar.bz2
          tar -xf libusb-1.0.28.tar.bz2
          cd libusb-1.0.28
          ./configure --disable-shared --enable-static --disable-udev LDFLAGS="-static"
          make -j$(nproc)
          sudo make install
          cd ..

      - name: Build ipwnder
        run: make -j$(nproc) LDFLAGS="-L/usr/local/lib -fuse-ld=lld" CC=clang LIBS="-ldl -lusb-1.0 -pthread -lcrypto"

      - name: Zip ipwnder
        run: zip -r ipwnder_linux-${{ matrix.arch.name }}.zip pwnedDFU

      - name: Update latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload latest \
            ipwnder_linux-${{ matrix.arch.name }}.zip \
            --clobber -R ${{ github.repository }}

          gh release edit latest \
            --title "Latest" \
            --target ${{ github.sha }} -R ${{ github.repository }}
